# Generated by Django 4.1.3 on 2022-12-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='video',
            field=models.FileField(null=True, upload_to='blog_video'),
        ),
    ]
